-- Project Afyon — personal chance games sharing the server-authoritative ₳D wallet.
-- Animations are client-local; wallet mutation and result generation are server-side.

create table if not exists public.chance_plays (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_key text not null check (game_key in (
    'marble_race','duck_derby','snail_league','afmb_wheel',
    'memur_box','chicken_run','coin_flip','marble_royale'
  )),
  stake bigint not null check (stake >= 10),
  choice text,
  result jsonb not null default '{}'::jsonb,
  multiplier numeric(8,2) not null default 0,
  payout bigint not null default 0 check (payout >= 0),
  created_at timestamptz not null default now()
);

alter table public.chance_plays enable row level security;

drop policy if exists "chance_plays_select_own" on public.chance_plays;
create policy "chance_plays_select_own"
on public.chance_plays
for select
to authenticated
using ((select auth.uid()) = user_id);

revoke all on public.chance_plays from anon;
grant select on public.chance_plays to authenticated;

create index if not exists chance_plays_user_created_idx
on public.chance_plays(user_id, created_at desc);

create or replace function public.play_chance_game(
  p_game_key text,
  p_stake bigint,
  p_choice text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_balance bigint;
  v_winner text;
  v_multiplier numeric(8,2) := 0;
  v_payout bigint := 0;
  v_result jsonb := '{}'::jsonb;
  v_play_id bigint;
  v_roll integer;
  v_valid_choices text[];
begin
  if v_user is null then
    raise exception 'Giriş yapman gerekiyor.';
  end if;

  if p_stake is null or p_stake < 10 then
    raise exception 'Minimum oyun miktarı 10 ₳D.';
  end if;

  if p_stake > 1000000 then
    raise exception 'Tek oyun için üst sınır 1.000.000 ₳D.';
  end if;

  select balance into v_balance
  from public.wallets
  where user_id = v_user
  for update;

  if not found then raise exception 'Cüzdan bulunamadı.'; end if;
  if v_balance < p_stake then raise exception 'Yetersiz ₳D.'; end if;

  case p_game_key
    when 'coin_flip' then
      v_valid_choices := array['HEADS','TAILS'];
      if p_choice is null or not (upper(p_choice) = any(v_valid_choices)) then raise exception 'Yazı veya tura seç.'; end if;
      v_winner := v_valid_choices[1 + floor(random()*2)::int];
      if upper(p_choice)=v_winner then v_multiplier := 1.95; end if;
      v_result := jsonb_build_object('winner',v_winner);

    when 'marble_race' then
      v_valid_choices := array['BLUE','RED','YELLOW','GREEN','PURPLE','ORANGE','WHITE','BLACK'];
      if p_choice is null or not (upper(p_choice) = any(v_valid_choices)) then raise exception 'Bir bilye seç.'; end if;
      v_winner := v_valid_choices[1 + floor(random()*8)::int];
      if upper(p_choice)=v_winner then v_multiplier := 7.20; end if;
      v_result := jsonb_build_object('winner',v_winner);

    when 'duck_derby' then
      v_valid_choices := array['D1','D2','D3','D4','D5','D6'];
      if p_choice is null or not (upper(p_choice) = any(v_valid_choices)) then raise exception 'Bir ördek seç.'; end if;
      v_winner := v_valid_choices[1 + floor(random()*6)::int];
      if upper(p_choice)=v_winner then v_multiplier := 5.40; end if;
      v_result := jsonb_build_object('winner',v_winner);

    when 'snail_league' then
      v_valid_choices := array['S1','S2','S3','S4','S5'];
      if p_choice is null or not (upper(p_choice) = any(v_valid_choices)) then raise exception 'Bir salyangoz seç.'; end if;
      v_winner := v_valid_choices[1 + floor(random()*5)::int];
      if upper(p_choice)=v_winner then v_multiplier := 4.50; end if;
      v_result := jsonb_build_object('winner',v_winner);

    when 'memur_box' then
      v_valid_choices := array['BOX1','BOX2','BOX3'];
      if p_choice is null or not (upper(p_choice) = any(v_valid_choices)) then raise exception 'Bir kutu seç.'; end if;
      v_winner := v_valid_choices[1 + floor(random()*3)::int];
      if upper(p_choice)=v_winner then v_multiplier := 2.70; end if;
      v_result := jsonb_build_object('winner',v_winner);

    when 'chicken_run' then
      v_valid_choices := array['C1','C2','C3','C4','C5','C6'];
      if p_choice is null or not (upper(p_choice) = any(v_valid_choices)) then raise exception 'Bir tavuk seç.'; end if;
      v_winner := v_valid_choices[1 + floor(random()*6)::int];
      if upper(p_choice)=v_winner then v_multiplier := 5.40; end if;
      v_result := jsonb_build_object('winner',v_winner);

    when 'marble_royale' then
      v_valid_choices := array['R1','R2','R3','R4','R5','R6','R7','R8','R9','R10','R11','R12','R13','R14','R15','R16'];
      if p_choice is null or not (upper(p_choice) = any(v_valid_choices)) then raise exception 'Bir royale bilyesi seç.'; end if;
      v_winner := v_valid_choices[1 + floor(random()*16)::int];
      if upper(p_choice)=v_winner then v_multiplier := 14.40; end if;
      v_result := jsonb_build_object('winner',v_winner);

    when 'afmb_wheel' then
      v_roll := 1 + floor(random()*8)::int;
      case v_roll
        when 1 then v_multiplier := 0.00; v_winner := 'EVRAK_KAYIP';
        when 2 then v_multiplier := 0.00; v_winner := 'OGLEDEN_SONRA_GEL';
        when 3 then v_multiplier := 0.50; v_winner := 'YARIM_MAAS';
        when 4 then v_multiplier := 0.80; v_winner := 'KESINTI';
        when 5 then v_multiplier := 1.00; v_winner := 'AYNEN_IADE';
        when 6 then v_multiplier := 1.20; v_winner := 'MESAİ';
        when 7 then v_multiplier := 1.50; v_winner := 'IKRAMIYE';
        when 8 then v_multiplier := 2.00; v_winner := 'MUHASEBE_HATASI';
      end case;
      v_result := jsonb_build_object('winner',v_winner,'segment',v_roll);

    else
      raise exception 'Bilinmeyen şans oyunu.';
  end case;

  v_payout := round(p_stake * v_multiplier);

  update public.wallets
  set balance = balance - p_stake + v_payout,
      updated_at = now()
  where user_id = v_user
  returning balance into v_balance;

  insert into public.chance_plays(user_id,game_key,stake,choice,result,multiplier,payout)
  values(v_user,p_game_key,p_stake,upper(p_choice),v_result,v_multiplier,v_payout)
  returning id into v_play_id;

  return jsonb_build_object(
    'play_id',v_play_id,'game_key',p_game_key,'choice',upper(p_choice),
    'result',v_result,'multiplier',v_multiplier,'payout',v_payout,'balance',v_balance
  );
end;
$$;

revoke all on function public.play_chance_game(text,bigint,text) from public, anon;
grant execute on function public.play_chance_game(text,bigint,text) to authenticated;
