-- Applied Supabase migration: rosters_2026_27_parody_localized


-- Project Afyon 0.26 — 2026/27 parody roster pass.
-- Türkiye Crown League mirrors current 2026/27 analogue squads.
-- Other players are localized fictional/parody names, with a small foreign-player mix.

alter table public.players add column if not exists source_player_name text;
alter table public.players add column if not exists roster_season text not null default '2026-27';
alter table public.players add column if not exists is_roster_mirror boolean not null default false;

create table if not exists private.player_roster_templates (
  club_name text not null,
  slot smallint not null,
  source_player_name text not null,
  parody_name text not null,
  position text not null,
  age smallint not null,
  nationality text not null,
  season text not null default '2026-27',
  primary key(club_name,slot)
);

delete from private.player_roster_templates where season='2026-27' and club_name in ('Galata Aslanları','Kadıköy Feneri','Boğaziçi Kartalları','Karadeniz Fırtınası','Başakşehir Birlik','İzmir Körfez','Samsun Kızıl Liman','Rize Çay Birliği','Konya Bozkır','Kocaeli Körfez','Alanya Sahil','Gaziantep Fıstıkspor','Ankara Gençlik','Kasımpaşa Tersane','Eyüp Haliç','Diyarbakır Surlar','Erzurum Ayaz','Çorum Leblebi');

insert into private.player_roster_templates(club_name,slot,source_player_name,parody_name,position,age,nationality)
values
('Galata Aslanları',1,'Uğurcan Çakır','Uğurcan Çakıro','GK',30,'Türkiye'),
('Galata Aslanları',2,'Jankat Yılmaz','Jankat Yılmazz','GK',22,'Türkiye'),
('Galata Aslanları',3,'Abdülkerim Bardakcı','Abdülkerim Bardakcın','DEF',32,'Türkiye'),
('Galata Aslanları',4,'Davinson Sanchez','Davinson Sanchezz','DEF',30,'Kolombiya'),
('Galata Aslanları',5,'Wilfried Singo','Wilfried Singoo','DEF',25,'Fildişi Sahili'),
('Galata Aslanları',6,'Ismail Jakobs','Ismail Jakobso','DEF',27,'Senegal'),
('Galata Aslanları',7,'Eren Elmalı','Eren Elmalın','DEF',26,'Türkiye'),
('Galata Aslanları',8,'Kaan Ayhan','Kaan Ayhano','DEF',31,'Türkiye'),
('Galata Aslanları',9,'Kazımcan Karataş','Kazımcan Karataşo','DEF',23,'Türkiye'),
('Galata Aslanları',10,'Aleksey Batrakov','Aleksey Batrako','MID',21,'Rusya'),
('Galata Aslanları',11,'Gabriel Sara','Gabriel Sarao','MID',27,'Brezilya'),
('Galata Aslanları',12,'Lucas Torreira','Lucas Torrero','MID',30,'Uruguay'),
('Galata Aslanları',13,'Mario Lemina','Mario Lemino','MID',33,'Gabon'),
('Galata Aslanları',14,'İlkay Gündoğan','İlkay Gündoğano','MID',35,'Türkiye'),
('Galata Aslanları',15,'Lesley Ugochukwu','Lesley Ugochukwun','MID',22,'Fransa'),
('Galata Aslanları',16,'Renato Nhaga','Renato Nhagan','MID',19,'Gine-Bissau'),
('Galata Aslanları',17,'Victor Osimhen','Victy Osimha','FWD',27,'Nijerya'),
('Galata Aslanları',18,'Rafael Leao','Rafael Leaon','FWD',27,'Portekiz'),
('Galata Aslanları',19,'Leroy Sane','Leroy Saney','FWD',30,'Almanya'),
('Galata Aslanları',20,'Barış Alper Yılmaz','Barış Alper Yılmız','FWD',26,'Türkiye'),
('Galata Aslanları',21,'Yunus Akgün','Yunus Akgüno','FWD',26,'Türkiye'),
('Galata Aslanları',22,'Deniz Gül','Deniz Gülo','FWD',22,'Türkiye'),
('Kadıköy Feneri',1,'Ederson','Nedersın','GK',33,'Brezilya'),
('Kadıköy Feneri',2,'Mert Günok','Mert Günoko','GK',37,'Türkiye'),
('Kadıköy Feneri',3,'Nathan Ake','Natan Akke','DEF',31,'Hollanda'),
('Kadıköy Feneri',4,'Milan Skriniar','Milan Skrinyar','DEF',31,'Slovakya'),
('Kadıköy Feneri',5,'Nelson Semedo','Nelson Semedon','DEF',32,'Portekiz'),
('Kadıköy Feneri',6,'Archie Brown','Archie Browno','DEF',24,'İngiltere'),
('Kadıköy Feneri',7,'Levent Mercan','Levent Mercano','DEF',25,'Türkiye'),
('Kadıköy Feneri',8,'Kojo Peprah Oppong','Kojo Peprah Oppongo','DEF',22,'Gana'),
('Kadıköy Feneri',9,'Ognjen Mimovic','Ognjen Mimovico','DEF',22,'Sırbistan'),
('Kadıköy Feneri',10,'Matteo Guendouzi','Mateo Guendouzo','MID',27,'Fransa'),
('Kadıköy Feneri',11,'N''Golo Kante','N''Golo Kantee','MID',35,'Fransa'),
('Kadıköy Feneri',12,'Marco Asensio','Marko Asensiyo','MID',30,'İspanya'),
('Kadıköy Feneri',13,'İsmail Yüksek','İsmail Yükseko','MID',27,'Türkiye'),
('Kadıköy Feneri',14,'İrfan Can Kahveci','İrfan Can Kahvecin','MID',31,'Türkiye'),
('Kadıköy Feneri',15,'Mert Hakan Yandaş','Mert Hakan Yandaşo','MID',32,'Türkiye'),
('Kadıköy Feneri',16,'Bartuğ Elmaz','Bartuğ Elmazz','MID',23,'Türkiye'),
('Kadıköy Feneri',17,'Mason Greenwood','Mason Greenwud','FWD',24,'İngiltere'),
('Kadıköy Feneri',18,'Romelu Lukaku','Romelu Lukako','FWD',33,'Belçika'),
('Kadıköy Feneri',19,'Kerem Aktürkoğlu','Kerem Aktüroğlu','FWD',27,'Türkiye'),
('Kadıköy Feneri',20,'Vedat Muriqi','Vedat Muriqo','FWD',32,'Kosova'),
('Kadıköy Feneri',21,'Oğuz Aydın','Oğuz Aydıno','FWD',25,'Türkiye'),
('Kadıköy Feneri',22,'Dorgeles Nene','Dorgeles Neno','FWD',23,'Mali'),
('Boğaziçi Kartalları',1,'Alexander Nübel','Aleks Nübelo','GK',29,'Almanya'),
('Boğaziçi Kartalları',2,'Doğan Alemdar','Doğan Alemdaro','GK',24,'Türkiye'),
('Boğaziçi Kartalları',3,'Emmanuel Agbadou','Emmanuel Agbadoun','DEF',29,'Fildişi Sahili'),
('Boğaziçi Kartalları',4,'Tiago Djalo','Tiago Djalon','DEF',26,'Portekiz'),
('Boğaziçi Kartalları',5,'Michael Amir Murillo','Michael Amir Murillon','DEF',30,'Panama'),
('Boğaziçi Kartalları',6,'Kassoum Ouattara','Kassoum Ouattaran','DEF',21,'Fransa'),
('Boğaziçi Kartalları',7,'Emirhan Topçu','Emirhan Topçun','DEF',25,'Türkiye'),
('Boğaziçi Kartalları',8,'Rıdvan Yılmaz','Rıdvan Yılmazz','DEF',25,'Türkiye'),
('Boğaziçi Kartalları',9,'Taylan Bulut','Taylan Buluto','DEF',20,'Türkiye'),
('Boğaziçi Kartalları',10,'Orkun Kökçü','Orkun Kökçuo','MID',25,'Türkiye'),
('Boğaziçi Kartalları',11,'Wilfred Ndidi','Wilfred Ndidio','MID',29,'Nijerya'),
('Boğaziçi Kartalları',12,'Salih Özcan','Salih Özcano','MID',28,'Türkiye'),
('Boğaziçi Kartalları',13,'Fabio Miretti','Fabio Mirettin','MID',23,'İtalya'),
('Boğaziçi Kartalları',14,'Junior Olaitan','Junior Olaitano','MID',24,'Benin'),
('Boğaziçi Kartalları',15,'Kartal Kayra Yılmaz','Kartal Kayra Yılmazz','MID',25,'Türkiye'),
('Boğaziçi Kartalları',16,'Milot Rashica','Milot Rashiko','MID',30,'Kosova'),
('Boğaziçi Kartalları',17,'Dusan Vlahovic','Dusan Vlahovik','FWD',26,'Sırbistan'),
('Boğaziçi Kartalları',18,'Leandro Trossard','Leandro Trossardo','FWD',31,'Belçika'),
('Boğaziçi Kartalları',19,'Vaclav Cerny','Vaclav Cernyo','FWD',28,'Çekya'),
('Boğaziçi Kartalları',20,'Hyeon-Gyu Oh','Hyeon-Gyu Oho','FWD',25,'Güney Kore'),
('Boğaziçi Kartalları',21,'Ernest Poku','Ernest Pokun','FWD',22,'Hollanda'),
('Boğaziçi Kartalları',22,'Semih Kılıçsoy','Semih Kılıçso','FWD',21,'Türkiye'),
('Karadeniz Fırtınası',1,'Andre Onana','Andre Onano','GK',30,'Kamerun'),
('Karadeniz Fırtınası',2,'Onuralp Çevikkan','Onuralp Çevikkano','GK',20,'Türkiye'),
('Karadeniz Fırtınası',3,'Stefan Savic','Stefan Savico','DEF',35,'Karadağ'),
('Karadeniz Fırtınası',4,'Samet Akaydın','Samet Akaydıno','DEF',32,'Türkiye'),
('Karadeniz Fırtınası',5,'Cenk Özkaçar','Cenk Özkaçaro','DEF',25,'Türkiye'),
('Karadeniz Fırtınası',6,'Chibuike Nwaiwu','Chibuike Nwaiwun','DEF',23,'Nijerya'),
('Karadeniz Fırtınası',7,'Sidny Lopes Cabral','Sidny Lopes Cabralo','DEF',24,'Yeşil Burun'),
('Karadeniz Fırtınası',8,'Wagner Pina','Wagner Pinan','DEF',23,'Yeşil Burun'),
('Karadeniz Fırtınası',9,'Mustafa Eskihellaç','Mustafa Eskihellaço','DEF',29,'Türkiye'),
('Karadeniz Fırtınası',10,'Fabinho','Fabinyo','MID',32,'Brezilya'),
('Karadeniz Fırtınası',11,'Ruslan Malinovskyi','Ruslan Malinovskyin','MID',33,'Ukrayna'),
('Karadeniz Fırtınası',12,'Ernest Muci','Ernest Mucin','MID',25,'Arnavutluk'),
('Karadeniz Fırtınası',13,'Ozan Tufan','Ozan Tufano','MID',31,'Türkiye'),
('Karadeniz Fırtınası',14,'Okay Yokuşlu','Okay Yokuşlio','MID',32,'Türkiye'),
('Karadeniz Fırtınası',15,'Benjamin Bouchouari','Benjamin Bouchouarin','MID',24,'Fas'),
('Karadeniz Fırtınası',16,'Melih Kabasakal','Melih Kabasakalo','MID',30,'Türkiye'),
('Karadeniz Fırtınası',17,'Mohamed Salah','Mo Salahh','FWD',34,'Mısır'),
('Karadeniz Fırtınası',18,'Paul Onuachu','Paul Onuaçu','FWD',32,'Nijerya'),
('Karadeniz Fırtınası',19,'Franculino Dju','Franculino Djun','FWD',22,'Gine-Bissau'),
('Karadeniz Fırtınası',20,'Doğuhan Aral Şimşir','Doğuhan Aral Şimşiro','FWD',24,'Türkiye'),
('Karadeniz Fırtınası',21,'Noah Saviolo','Noah Saviolon','FWD',22,'Almanya'),
('Karadeniz Fırtınası',22,'Mehmet Umut Nayir','Mehmet Umut Nayiro','FWD',33,'Türkiye'),
('Başakşehir Birlik',1,'Deniz Dilmen','Deniz Dilmeno','GK',21,'Türkiye'),
('Başakşehir Birlik',2,'Muhammed Şengezer','Muhammed Şengezero','GK',29,'Türkiye'),
('Başakşehir Birlik',3,'Jerome Opoku','Jerome Opokun','DEF',27,'Gana'),
('Başakşehir Birlik',4,'Emin Bayram','Emin Bayramo','DEF',23,'Türkiye'),
('Başakşehir Birlik',5,'Christopher Operi','Christopher Operin','DEF',29,'Fildişi Sahili'),
('Başakşehir Birlik',6,'Michal Karbownik','Michal Karbowniko','DEF',25,'Polonya'),
('Başakşehir Birlik',7,'Ousseynou Ba','Ousseynou Ban','DEF',30,'Senegal'),
('Başakşehir Birlik',8,'Hamza Güreler','Hamza Gürelero','DEF',20,'Türkiye'),
('Başakşehir Birlik',9,'Saba Kharebashvili','Saba Kharebashvilin','DEF',18,'Gürcistan'),
('Başakşehir Birlik',10,'Olivier Kemen','Olivier Kemeno','MID',30,'Kamerun'),
('Başakşehir Birlik',11,'Jakub Kaluzinski','Jakub Kaluzinskin','MID',23,'Polonya'),
('Başakşehir Birlik',12,'Umut Güneş','Umut Güneşo','MID',26,'Türkiye'),
('Başakşehir Birlik',13,'Ömer Şahiner','Ömer Şahinero','MID',34,'Türkiye'),
('Başakşehir Birlik',14,'Onur Ergün','Onur Ergüno','MID',33,'Türkiye'),
('Başakşehir Birlik',15,'Miguel Crespo','Miguel Crespon','MID',30,'Portekiz'),
('Başakşehir Birlik',16,'Abbosbek Fayzullaev','Abbosbek Fayzullaevo','MID',22,'Özbekistan'),
('Başakşehir Birlik',17,'Eldor Shomurodov','Eldor Şomurodo','FWD',31,'Özbekistan'),
('Başakşehir Birlik',18,'Davie Selke','Davie Selken','FWD',31,'Almanya'),
('Başakşehir Birlik',19,'Andreas Skov Olsen','Andreas Skov Olseno','FWD',26,'Danimarka'),
('Başakşehir Birlik',20,'Yusuf Sarı','Yusuf Sarın','FWD',27,'Türkiye'),
('Başakşehir Birlik',21,'Bertuğ Yıldırım','Bertuğ Yıldırımo','FWD',24,'Türkiye'),
('Başakşehir Birlik',22,'Umut Bozok','Umut Bozoko','FWD',29,'Türkiye'),
('İzmir Körfez',1,'Luka Gugeshashvili','Luka Gugeshashvilin','GK',27,'Gürcistan'),
('İzmir Körfez',2,'Arda Özçimen','Arda Özçimeno','GK',24,'Türkiye'),
('İzmir Körfez',3,'Allan Godoi','Allan Godoin','DEF',33,'Brezilya'),
('İzmir Körfez',4,'Taha Altıkardeş','Taha Altıkardeşo','DEF',23,'Türkiye'),
('İzmir Körfez',5,'Malcom Bokele','Malcom Bokelen','DEF',26,'Kamerun'),
('İzmir Körfez',6,'Ege Yıldırım','Ege Yıldırımo','DEF',19,'Türkiye'),
('İzmir Körfez',7,'Noah Sonko Sundberg','Noah Sonko Sundbergo','DEF',30,'Gambiya'),
('İzmir Körfez',8,'Furkan Bayır','Furkan Bayıro','DEF',26,'Türkiye'),
('İzmir Körfez',9,'Ogun Bayrak','Ogun Bayrako','DEF',27,'Türkiye'),
('İzmir Körfez',10,'Richard Akonnor','Richard Akonnoro','MID',22,'Gana'),
('İzmir Körfez',11,'Faustino Anjorin','Faustino Anjorino','MID',24,'İngiltere'),
('İzmir Körfez',12,'Alexis Antunes','Alexis Antuneso','MID',26,'İsviçre'),
('İzmir Körfez',13,'Efkan Bekiroğlu','Efkan Bekiroğlun','MID',31,'Türkiye'),
('İzmir Körfez',14,'Rhaldney Gomes','Rhaldney Gomeso','MID',27,'Brezilya'),
('İzmir Körfez',15,'Alex Matos','Alex Matoso','MID',21,'İngiltere'),
('İzmir Körfez',16,'Novatus Miroshi','Novatus Miroshin','MID',24,'Tanzanya'),
('İzmir Körfez',17,'Andre Henrique','Andre Henriquen','FWD',24,'Brezilya'),
('İzmir Körfez',18,'Sinclair Armstrong','Sinclair Armstrongo','FWD',23,'İrlanda'),
('İzmir Körfez',19,'Gökdeniz Bayrakdar','Gökdeniz Bayrakdaro','FWD',24,'Türkiye'),
('İzmir Körfez',20,'Bekir Turaç Böke','Bekir Turaç Böken','FWD',27,'Türkiye'),
('İzmir Körfez',21,'Janderson','Jandersono','FWD',27,'Brezilya'),
('İzmir Körfez',22,'Juan Santos','Juan Santoso','FWD',24,'Brezilya'),
('Samsun Kızıl Liman',1,'Okan Kocuk','Okan Kocuko','GK',31,'Türkiye'),
('Samsun Kızıl Liman',2,'Albert Posiadala','Albert Posiadalan','GK',23,'Polonya'),
('Samsun Kızıl Liman',3,'Toni Borevkovic','Toni Borevkovico','DEF',29,'Hırvatistan'),
('Samsun Kızıl Liman',4,'Rick van Drongelen','Rick van Drongeleno','DEF',28,'Hollanda'),
('Samsun Kızıl Liman',5,'Lubomir Satka','Lubomir Satkan','DEF',30,'Slovakya'),
('Samsun Kızıl Liman',6,'Yunus Emre Çift','Yunus Emre Çifto','DEF',23,'Türkiye'),
('Samsun Kızıl Liman',7,'Logi Tomasson','Logi Tomassono','DEF',26,'İzlanda'),
('Samsun Kızıl Liman',8,'Soner Gönül','Soner Gönülo','DEF',29,'Türkiye'),
('Samsun Kızıl Liman',9,'Joe Mendes','Joe Mendeso','DEF',24,'İsveç'),
('Samsun Kızıl Liman',10,'Antoine Makoumbou','Antoine Makoumboun','MID',28,'Kongo'),
('Samsun Kızıl Liman',11,'Celil Yüksel','Celil Yükselo','MID',28,'Türkiye'),
('Samsun Kızıl Liman',12,'Olivier Ntcham','Olivier Ntchamo','MID',30,'Kamerun'),
('Samsun Kızıl Liman',13,'Eyüp Aydın','Eyüp Aydıno','MID',22,'Türkiye'),
('Samsun Kızıl Liman',14,'Soner Aydoğdu','Soner Aydoğdun','MID',35,'Türkiye'),
('Samsun Kızıl Liman',15,'Afonso Sousa','Afonso Sousan','MID',26,'Portekiz'),
('Samsun Kızıl Liman',16,'Carlo Holse','Carlo Holsen','MID',27,'Danimarka'),
('Samsun Kızıl Liman',17,'Emre Kılınç','Emre Kılınço','FWD',32,'Türkiye'),
('Samsun Kızıl Liman',18,'Tanguy Coulibaly','Tanguy Coulibalyo','FWD',25,'Fransa'),
('Samsun Kızıl Liman',19,'Anthony Musaba','Anthony Musaban','FWD',25,'Hollanda'),
('Samsun Kızıl Liman',20,'Polat Yaldır','Polat Yaldıro','FWD',23,'Türkiye'),
('Samsun Kızıl Liman',21,'Cherif Ndiaye','Cherif Ndiayen','FWD',30,'Senegal'),
('Samsun Kızıl Liman',22,'Marius Mouandilmadji','Marius Mouandilmadjin','FWD',28,'Çad'),
('Rize Çay Birliği',1,'Yahia Fofana','Yahia Fofanan','GK',26,'Fildişi Sahili'),
('Rize Çay Birliği',2,'Zafer Görgen','Zafer Görgeno','GK',26,'Türkiye'),
('Rize Çay Birliği',3,'Khusniddin Aliqulov','Khusniddin Aliqulovo','DEF',27,'Özbekistan'),
('Rize Çay Birliği',4,'Attila Mocsi','Attila Mocsin','DEF',26,'Macaristan'),
('Rize Çay Birliği',5,'Zakaria Ariss','Zakaria Arisso','DEF',21,'Fransa'),
('Rize Çay Birliği',6,'Anıl Yaşar','Anıl Yaşaro','DEF',24,'Türkiye'),
('Rize Çay Birliği',7,'Tayyip Talha Sanuç','Tayyip Talha Sanuço','DEF',26,'Türkiye'),
('Rize Çay Birliği',8,'Modibo Sagnan','Modibo Sagnano','DEF',27,'Mali'),
('Rize Çay Birliği',9,'Taha Şahin','Taha Şahino','DEF',26,'Türkiye'),
('Rize Çay Birliği',10,'Dal Varesanovic','Dal Varesanovico','MID',25,'Bosna-Hersek'),
('Rize Çay Birliği',11,'Taylan Antalyalı','Taylan Antalyalın','MID',31,'Türkiye'),
('Rize Çay Birliği',12,'Qazim Laçi','Qazim Laçin','MID',30,'Arnavutluk'),
('Rize Çay Birliği',13,'Eren Emre Aydın','Eren Emre Aydıno','MID',22,'Türkiye'),
('Rize Çay Birliği',14,'Mithat Pala','Mithat Palan','MID',26,'Türkiye'),
('Rize Çay Birliği',15,'Altın Zeqiri','Altın Zeqirin','MID',25,'Kosova'),
('Rize Çay Birliği',16,'Yakup Ayan','Yakup Ayano','MID',20,'Türkiye'),
('Rize Çay Birliği',17,'Valentin Mihaila','Valentin Mihailan','FWD',26,'Romanya'),
('Rize Çay Birliği',18,'Ali Sowe','Ali Sowen','FWD',32,'Gambiya'),
('Rize Çay Birliği',19,'Ibrahim Olawoyin','Ibrahim Olawoyino','FWD',28,'Nijerya'),
('Rize Çay Birliği',20,'Adedire Mebude','Adedire Mebuden','FWD',22,'İskoçya'),
('Rize Çay Birliği',21,'Ahmed Kutucu','Ahmed Kutucun','FWD',26,'Türkiye'),
('Rize Çay Birliği',22,'Emrecan Bulut','Emrecan Buluto','FWD',24,'Türkiye'),
('Konya Bozkır',1,'Deniz Ertaş','Deniz Ertaşo','GK',21,'Türkiye'),
('Konya Bozkır',2,'Bahadır Güngördü','Bahadır Güngördün','GK',30,'Türkiye'),
('Konya Bozkır',3,'Yhoan Andzouana','Yhoan Andzouanan','DEF',29,'Kongo'),
('Konya Bozkır',4,'Chidozie Awaziem','Chidozie Awaziemo','DEF',29,'Nijerya'),
('Konya Bozkır',5,'Rayyan Baniya','Rayyan Baniyan','DEF',27,'Türkiye'),
('Konya Bozkır',6,'Arif Boşluk','Arif Boşluko','DEF',23,'Türkiye'),
('Konya Bozkır',7,'Adil Demirbağ','Adil Demirbağo','DEF',28,'Türkiye'),
('Konya Bozkır',8,'Arthur Masuaku','Arthur Masuakun','DEF',32,'Kongo DC'),
('Konya Bozkır',9,'Uğurcan Yazğılı','Uğurcan Yazğılın','DEF',27,'Türkiye'),
('Konya Bozkır',10,'Enis Bardhi','Enis Bardhio','MID',31,'Kuzey Makedonya'),
('Konya Bozkır',11,'Melih İbrahimoğlu','Melih İbrahimoğlun','MID',26,'Türkiye'),
('Konya Bozkır',12,'Marko Jevtovic','Marko Jevtovico','MID',33,'Sırbistan'),
('Konya Bozkır',13,'Rajmund Toth','Rajmund Totho','MID',22,'Macaristan'),
('Konya Bozkır',14,'Deniz Türüç','Deniz Türüço','MID',33,'Türkiye'),
('Konya Bozkır',15,'Da Mata','Da Matan','MID',20,'Brezilya'),
('Konya Bozkır',16,'Ebrima Colley','Ebrima Colleyo','MID',26,'Gambiya'),
('Konya Bozkır',17,'Mostafa Mohamed','Mostafa Mohammedo','FWD',28,'Mısır'),
('Konya Bozkır',18,'Enis Destan','Enis Destano','FWD',24,'Türkiye'),
('Konya Bozkır',19,'Jean-Luc Dompe','Jean-Luc Dompen','FWD',31,'Fransa'),
('Konya Bozkır',20,'Mohamed Fofana','Mohamed Fofanan','FWD',20,'Gine'),
('Konya Bozkır',21,'Eric Konate','Eric Konaten','FWD',21,'Fildişi Sahili'),
('Konya Bozkır',22,'Ibrahima Bah','Ibrahima Baho','FWD',21,'Gine'),
('Kocaeli Körfez',1,'Serhat Öztaşdelen','Serhat Öztaşdeleno','GK',22,'Türkiye'),
('Kocaeli Körfez',2,'Onurcan Piri','Onurcan Pirin','GK',32,'Türkiye'),
('Kocaeli Körfez',3,'Anfernee Dijksteel','Anfernee Dijksteelo','DEF',29,'Surinam'),
('Kocaeli Körfez',4,'Massadio Haidara','Massadio Haidaran','DEF',33,'Mali'),
('Kocaeli Körfez',5,'Matej Maglica','Matej Maglican','DEF',27,'Hırvatistan'),
('Kocaeli Körfez',6,'Emir Ortakaya','Emir Ortakayan','DEF',22,'Türkiye'),
('Kocaeli Körfez',7,'Tanguy Zoukrou','Tanguy Zoukroun','DEF',23,'Fransa'),
('Kocaeli Körfez',8,'Muharrem Cinan','Muharrem Cinano','DEF',28,'Türkiye'),
('Kocaeli Körfez',9,'Uğur Kaan Yıldız','Uğur Kaan Yıldızz','DEF',23,'Türkiye'),
('Kocaeli Körfez',10,'Tobias Gulliksen','Tobias Gullikseno','MID',23,'Norveç'),
('Kocaeli Körfez',11,'Berkan Kutlu','Berkan Kutlun','MID',28,'Türkiye'),
('Kocaeli Körfez',12,'Show','Showo','MID',27,'Angola'),
('Kocaeli Körfez',13,'Mahamadou Susoho','Mahamadou Susohon','MID',21,'İspanya'),
('Kocaeli Körfez',14,'Ege Bilim','Ege Bilimo','MID',20,'Türkiye'),
('Kocaeli Körfez',15,'Tayfur Bingöl','Tayfur Bingölo','MID',33,'Türkiye'),
('Kocaeli Körfez',16,'Haydar Karataş','Haydar Karataşo','MID',19,'Türkiye'),
('Kocaeli Körfez',17,'Florian Ayé','Florian Ayéo','FWD',29,'Fransa'),
('Kocaeli Körfez',18,'Gonçalo Sousa','Gonçalo Sousan','FWD',20,'Portekiz'),
('Kocaeli Körfez',19,'Makana Baku','Makana Bakun','FWD',28,'Almanya'),
('Kocaeli Körfez',20,'Metehan Altunbaş','Metehan Altunbaşo','FWD',23,'Türkiye'),
('Kocaeli Körfez',21,'Rigoberto Rivas','Rigoberto Rivaso','FWD',28,'Honduras'),
('Kocaeli Körfez',22,'Bedirhan Yıldız','Bedirhan Yıldızz','FWD',21,'Türkiye'),
('Alanya Sahil',1,'Paulo Victor','Paulo Victoro','GK',39,'Brezilya'),
('Alanya Sahil',2,'Mert Bayram','Mert Bayramo','GK',21,'Türkiye'),
('Alanya Sahil',3,'Ümit Akdağ','Ümit Akdağo','DEF',22,'Türkiye'),
('Alanya Sahil',4,'Fatih Aksoy','Fatih Aksoyo','DEF',28,'Türkiye'),
('Alanya Sahil',5,'Fidan Aliti','Fidan Alitin','DEF',32,'Kosova'),
('Alanya Sahil',6,'Nuno Lima','Nuno Liman','DEF',25,'Portekiz'),
('Alanya Sahil',7,'Bedirhan Özyurt','Bedirhan Özyurto','DEF',23,'Türkiye'),
('Alanya Sahil',8,'Florent Hadergjonaj','Florent Hadergjonajo','DEF',32,'Kosova'),
('Alanya Sahil',9,'Eymen Karataş','Eymen Karataşo','DEF',18,'Türkiye'),
('Alanya Sahil',10,'İzzet Çelik','İzzet Çeliko','MID',22,'Türkiye'),
('Alanya Sahil',11,'Emre Demir','Emre Demiro','MID',22,'Türkiye'),
('Alanya Sahil',12,'Baran Gezek','Baran Gezeko','MID',21,'Türkiye'),
('Alanya Sahil',13,'Ianis Hagi','Yanis Haggio','MID',27,'Romanya'),
('Alanya Sahil',14,'İbrahim Kaya','İbrahim Kayan','MID',25,'Türkiye'),
('Alanya Sahil',15,'Enes Keskin','Enes Keskino','MID',25,'Türkiye'),
('Alanya Sahil',16,'Maestro','Maestryo','MID',23,'Angola'),
('Alanya Sahil',17,'Ruan','Ruano','FWD',21,'Brezilya'),
('Alanya Sahil',18,'Omar Ben Ali','Omar Ben Alin','FWD',21,'Tunus'),
('Alanya Sahil',19,'Meschack Elia','Meschack Elian','FWD',29,'Kongo DC'),
('Alanya Sahil',20,'Arda Usluoğlu','Arda Usluoğlun','FWD',19,'Türkiye'),
('Alanya Sahil',21,'Hwang Ui-Jo','Hwang Ui-Jon','FWD',34,'Güney Kore'),
('Alanya Sahil',22,'Yusuf Özdemir','Yusuf Özdemiro','FWD',25,'Türkiye'),
('Gaziantep Fıstıkspor',1,'Kacper Tobiasz','Kacper Tobiaszz','GK',23,'Polonya'),
('Gaziantep Fıstıkspor',2,'Ataberk Dadakdeniz','Ataberk Dadakdenizz','GK',27,'Türkiye'),
('Gaziantep Fıstıkspor',3,'Abakar Sylla','Abakar Syllan','DEF',23,'Fildişi Sahili'),
('Gaziantep Fıstıkspor',4,'Efe Sarıkaya','Efe Sarıkayan','DEF',21,'Türkiye'),
('Gaziantep Fıstıkspor',5,'Luis Perez','Luis Perezz','DEF',31,'İspanya'),
('Gaziantep Fıstıkspor',6,'Ulrich Meleke','Ulrich Meleken','DEF',27,'Kamerun'),
('Gaziantep Fıstıkspor',7,'Myenty Abena','Myenty Abenan','DEF',31,'Surinam'),
('Gaziantep Fıstıkspor',8,'Kerim Çalhanoğlu','Kerim Çalhanoğlun','DEF',24,'Türkiye'),
('Gaziantep Fıstıkspor',9,'Florin Stefan','Florin Stefano','DEF',30,'Romanya'),
('Gaziantep Fıstıkspor',10,'Kacper Kozlowski','Kasper Kozlovski','MID',22,'Polonya'),
('Gaziantep Fıstıkspor',11,'Juninho Bacuna','Juninho Bacunan','MID',29,'Curaçao'),
('Gaziantep Fıstıkspor',12,'Drissa Camara','Drissa Camaran','MID',24,'Fildişi Sahili'),
('Gaziantep Fıstıkspor',13,'Victor Gidado','Victor Gidadon','MID',21,'Nijerya'),
('Gaziantep Fıstıkspor',14,'Deian Sorescu','Deian Sorescun','MID',29,'Romanya'),
('Gaziantep Fıstıkspor',15,'Ogün Özçiçek','Ogün Özçiçeko','MID',27,'Türkiye'),
('Gaziantep Fıstıkspor',16,'Alexandru Maxim','Alexandro Maximo','MID',36,'Romanya'),
('Gaziantep Fıstıkspor',17,'Trivante Stewart','Trivante Stewarto','FWD',26,'Jamaika'),
('Gaziantep Fıstıkspor',18,'Serdar Dursun','Serdar Dursuno','FWD',34,'Türkiye'),
('Gaziantep Fıstıkspor',19,'Sontje Hansen','Sontje Hanseno','FWD',24,'Hollanda'),
('Gaziantep Fıstıkspor',20,'Halil Dervişoğlu','Halil Dervişoğlun','FWD',26,'Türkiye'),
('Gaziantep Fıstıkspor',21,'Ali Osman Kalın','Ali Osman Kalıno','FWD',18,'Türkiye'),
('Gaziantep Fıstıkspor',22,'Muhammed Akmelek','Muhammed Akmeleko','FWD',17,'Türkiye'),
('Ankara Gençlik',1,'İrfan Can Eğribayat','İrfan Can Eğribayato','GK',28,'Türkiye'),
('Ankara Gençlik',2,'Emirzat Baycu','Emirzat Baycun','GK',19,'Türkiye'),
('Ankara Gençlik',3,'Metehan Baltacı','Metehan Baltacın','DEF',23,'Türkiye'),
('Ankara Gençlik',4,'Abdurrahim Dursun','Abdurrahim Dursuno','DEF',27,'Türkiye'),
('Ankara Gençlik',5,'Dimitrios Goutas','Dimitrios Goutaso','DEF',32,'Yunanistan'),
('Ankara Gençlik',6,'Pedro Pereira','Pedro Pereiran','DEF',28,'Portekiz'),
('Ankara Gençlik',7,'Fıratcan Üzüm','Fıratcan Üzümo','DEF',27,'Türkiye'),
('Ankara Gençlik',8,'Zan Zuzek','Zan Zuzeko','DEF',29,'Slovenya'),
('Ankara Gençlik',9,'Göktuğ Erdem','Göktuğ Erdemo','DEF',23,'Türkiye'),
('Ankara Gençlik',10,'Ousmane Diabate','Ousmane Diabaten','MID',18,'Mali'),
('Ankara Gençlik',11,'Peter Etebo','Peter Etebon','MID',30,'Nijerya'),
('Ankara Gençlik',12,'Ensar Kemaloğlu','Ensar Kemaloğlun','MID',27,'Türkiye'),
('Ankara Gençlik',13,'Moussa Kyabou','Moussa Kyaboun','MID',28,'Mali'),
('Ankara Gençlik',14,'Cheikh Niasse','Cheikh Niassen','MID',26,'Senegal'),
('Ankara Gençlik',15,'Franco Tongya','Franco Tongyan','MID',24,'İtalya'),
('Ankara Gençlik',16,'Salih Uçan','Salih Uçano','MID',32,'Türkiye'),
('Ankara Gençlik',17,'Tiago Gouveia','Tiago Gouveian','FWD',25,'Portekiz'),
('Ankara Gençlik',18,'Sekou Koita','Sekou Koitan','FWD',26,'Mali'),
('Ankara Gençlik',19,'Prince Martor','Prince Martoro','FWD',19,'Liberya'),
('Ankara Gençlik',20,'Adama Traore','Adama Traoren','FWD',31,'Mali'),
('Ankara Gençlik',21,'Erk Aslan','Erk Aslano','FWD',17,'Türkiye'),
('Ankara Gençlik',22,'Ayaz Özcan','Ayaz Özcano','FWD',16,'Türkiye'),
('Kasımpaşa Tersane',1,'Andreas Gianniotis','Andreas Giannioto','GK',33,'Yunanistan'),
('Kasımpaşa Tersane',2,'Ege Albayrak','Ege Albayrako','GK',19,'Türkiye'),
('Kasımpaşa Tersane',3,'Adem Arous','Adem Arouso','DEF',22,'Tunus'),
('Kasımpaşa Tersane',4,'Ahmet Taha Dağbaşı','Ahmet Taha Dağbaşın','DEF',21,'Türkiye'),
('Kasımpaşa Tersane',5,'Matei Cristian Ilie','Matei Cristian Ilien','DEF',23,'Romanya'),
('Kasımpaşa Tersane',6,'Jakob Jessen','Jakob Jesseno','DEF',22,'Danimarka'),
('Kasımpaşa Tersane',7,'Ayberk Karapo','Ayberk Karapon','DEF',22,'Türkiye'),
('Kasımpaşa Tersane',8,'Kevin Mouanga','Kevin Mouangan','DEF',26,'Fransa'),
('Kasımpaşa Tersane',9,'Claudio Winck','Claudio Wincko','DEF',32,'Brezilya'),
('Kasımpaşa Tersane',10,'Marcus Rafferty','Marcus Raffertyo','MID',22,'İngiltere'),
('Kasımpaşa Tersane',11,'Emirhan Boz','Emirhan Bozz','MID',20,'Türkiye'),
('Kasımpaşa Tersane',12,'Kerem Demirbay','Kerem Demirbayo','MID',33,'Türkiye'),
('Kasımpaşa Tersane',13,'Haris Hajradinovic','Haris Hajradinovico','MID',32,'Bosna-Hersek'),
('Kasımpaşa Tersane',14,'Elson Mendes','Elson Mendeso','MID',23,'Portekiz'),
('Kasımpaşa Tersane',15,'Mortadha Ben Ouanes','Mortadha Ben Ouaneso','MID',31,'Tunus'),
('Kasımpaşa Tersane',16,'Jesurun Rak-Sakyi','Jesurun Rak-Sakyin','MID',23,'İngiltere'),
('Kasımpaşa Tersane',17,'Adrian Benedyczak','Adrian Benedyczako','FWD',25,'Polonya'),
('Kasımpaşa Tersane',18,'Fousseni Diabate','Fousseni Diabaten','FWD',30,'Mali'),
('Kasımpaşa Tersane',19,'Thiemoko Diarra','Thiemoko Diarran','FWD',23,'Mali'),
('Kasımpaşa Tersane',20,'Güven Yalçın','Güven Yalçıno','FWD',27,'Türkiye'),
('Kasımpaşa Tersane',21,'Ali Yavuz Kol','Ali Yavuz Kolo','FWD',25,'Türkiye'),
('Kasımpaşa Tersane',22,'Sercan Deniz','Sercan Denizz','FWD',21,'Türkiye'),
('Eyüp Haliç',1,'Horatiu Moldovan','Horatiu Moldovano','GK',28,'Romanya'),
('Eyüp Haliç',2,'Emre Bilgin','Emre Bilgino','GK',22,'Türkiye'),
('Eyüp Haliç',3,'Jawad El Yamiq','Jawad El Yamiqo','DEF',34,'Fas'),
('Eyüp Haliç',4,'Zak Jules','Zak Juleso','DEF',29,'İskoçya'),
('Eyüp Haliç',5,'Simone Giordano','Simone Giordanon','DEF',24,'İtalya'),
('Eyüp Haliç',6,'Talha Ülvan','Talha Ülvano','DEF',25,'Türkiye'),
('Eyüp Haliç',7,'Anıl Yaşar','Anıl Yaşaro','DEF',24,'Türkiye'),
('Eyüp Haliç',8,'Yiğit Demir','Yiğit Demiro','DEF',22,'Türkiye'),
('Eyüp Haliç',9,'Diabel Ndoye','Diabel Ndoyen','DEF',18,'Senegal'),
('Eyüp Haliç',10,'David Costa','David Costan','MID',22,'Portekiz'),
('Eyüp Haliç',11,'Abdelhamid Sabiri','Abdelhamid Sabirin','MID',29,'Fas'),
('Eyüp Haliç',12,'Charles Raux Yao','Charles Raux Yaon','MID',24,'Fildişi Sahili'),
('Eyüp Haliç',13,'Hamza Akman','Hamza Akmano','MID',21,'Türkiye'),
('Eyüp Haliç',14,'Taşkın İlter','Taşkın İltero','MID',32,'Türkiye'),
('Eyüp Haliç',15,'Chandrel Massanga','Chandrel Massangan','MID',27,'Kongo'),
('Eyüp Haliç',16,'Christ Sadia','Christ Sadian','MID',22,'Fransa'),
('Eyüp Haliç',17,'Ahmed Abdullahi','Ahmed Abdullahin','FWD',22,'Nijerya'),
('Eyüp Haliç',18,'Yusuf Barası','Yusuf Barasın','FWD',23,'Türkiye'),
('Eyüp Haliç',19,'Lenny Pintor','Lenny Pintoro','FWD',26,'Fransa'),
('Eyüp Haliç',20,'Konrad Michalak','Konrad Michalako','FWD',28,'Polonya'),
('Eyüp Haliç',21,'Bilal Boutobba','Bilal Boutobban','FWD',28,'Cezayir'),
('Eyüp Haliç',22,'Mete Demir','Mete Demiro','FWD',28,'Türkiye'),
('Diyarbakır Surlar',1,'Alban Lafont','Alban Lafonto','GK',27,'Fildişi Sahili'),
('Diyarbakır Surlar',2,'Mustafa Burak Bozan','Mustafa Burak Bozano','GK',26,'Türkiye'),
('Diyarbakır Surlar',3,'David Bates','David Bateso','DEF',29,'İskoçya'),
('Diyarbakır Surlar',4,'Lumbardh Dellova','Lumbardh Dellovan','DEF',27,'Kosova'),
('Diyarbakır Surlar',5,'Umut Meraş','Umut Meraşo','DEF',30,'Türkiye'),
('Diyarbakır Surlar',6,'Ali Turap Bülbül','Ali Turap Bülbülo','DEF',21,'Türkiye'),
('Diyarbakır Surlar',7,'Mehmet Yeşil','Mehmet Yeşilo','DEF',28,'Türkiye'),
('Diyarbakır Surlar',8,'Amadou Cisse','Amadou Cissen','DEF',23,'Fransa'),
('Diyarbakır Surlar',9,'Miraç Acer','Miraç Acero','DEF',21,'Türkiye'),
('Diyarbakır Surlar',10,'Rayan Raveloson','Rayan Ravelozon','MID',29,'Madagaskar'),
('Diyarbakır Surlar',11,'Gökhan Gül','Gökhan Gülo','MID',28,'Almanya'),
('Diyarbakır Surlar',12,'Rayan Lutin','Rayan Lutino','MID',23,'Komorlar'),
('Diyarbakır Surlar',13,'Furkan Soyalp','Furkan Soyalpo','MID',31,'Türkiye'),
('Diyarbakır Surlar',14,'Cem Üstündağ','Cem Üstündağo','MID',25,'Türkiye'),
('Diyarbakır Surlar',15,'Dia Saba','Dio Saba','MID',33,'İsrail'),
('Diyarbakır Surlar',16,'Mohamed Khalil','Mohamed Khalilo','MID',25,'Suriye'),
('Diyarbakır Surlar',17,'Gift Orban','Gifti Orban','FWD',24,'Nijerya'),
('Diyarbakır Surlar',18,'Mbaye Diagne','Mbaye Diagno','FWD',34,'Senegal'),
('Diyarbakır Surlar',19,'Ermal Krasniqi','Ermal Krasniqo','FWD',28,'Kosova'),
('Diyarbakır Surlar',20,'Yira Sor','Yira Sorr','FWD',26,'Nijerya'),
('Diyarbakır Surlar',21,'Samuel Ballet','Samuel Balleto','FWD',25,'İsviçre'),
('Diyarbakır Surlar',22,'Dilhan Demir','Dilhan Demiro','FWD',23,'Almanya'),
('Erzurum Ayaz',1,'Matija Orbanic','Matija Orbanico','GK',26,'Hırvatistan'),
('Erzurum Ayaz',2,'Mahmut Ertuğrul Taşkıran','Mahmut Ertuğrul Taşkırano','GK',36,'Türkiye'),
('Erzurum Ayaz',3,'Festy Ebosele','Festy Eboselen','DEF',24,'İrlanda'),
('Erzurum Ayaz',4,'Amar Gerxhaliu','Amar Gerxhaliun','DEF',24,'Kosova'),
('Erzurum Ayaz',5,'Guram Giorbelidze','Guram Giorbelidzen','DEF',30,'Gürcistan'),
('Erzurum Ayaz',6,'Yakup Kırtay','Yakup Kırtayo','DEF',23,'Türkiye'),
('Erzurum Ayaz',7,'Nihad Mujakic','Nihad Mujakico','DEF',28,'Bosna-Hersek'),
('Erzurum Ayaz',8,'Orhan Ovacıklı','Orhan Ovacıklın','DEF',37,'Türkiye'),
('Erzurum Ayaz',9,'Mustafa Yumlu','Mustafa Yumlun','DEF',38,'Türkiye'),
('Erzurum Ayaz',10,'Sefa Akgün','Sefa Akgüno','MID',26,'Türkiye'),
('Erzurum Ayaz',11,'Brandon Baiye','Brandon Baiyen','MID',25,'Belçika'),
('Erzurum Ayaz',12,'Elisha Owusu','Elisha Owusun','MID',28,'Gana'),
('Erzurum Ayaz',13,'Martin Rodriguez','Martin Rodriguezz','MID',32,'Şili'),
('Erzurum Ayaz',14,'Lawrence Agyekum','Lawrence Agyekumo','MID',22,'Gana'),
('Erzurum Ayaz',15,'Emirhan Acar','Emirhan Acaro','MID',21,'Türkiye'),
('Erzurum Ayaz',16,'Mehmet Billor','Mehmet Billoro','MID',18,'Türkiye'),
('Erzurum Ayaz',17,'Nariman Akhundzade','Nariman Akhundzaden','FWD',22,'Azerbaycan'),
('Erzurum Ayaz',18,'Miguel Cardoso','Miguel Cardoson','FWD',32,'Portekiz'),
('Erzurum Ayaz',19,'Ibrahim Diabate','Ibrahim Diabaten','FWD',26,'Fildişi Sahili'),
('Erzurum Ayaz',20,'Mustafa Fettahoğlu','Mustafa Fettahoğlun','FWD',25,'Türkiye'),
('Erzurum Ayaz',21,'Gyrano Kerk','Gyrano Kerko','FWD',30,'Surinam'),
('Erzurum Ayaz',22,'Eren Tozlu','Eren Tozlun','FWD',35,'Türkiye'),
('Çorum Leblebi',1,'Marcos Felipe','Marcos Felipen','GK',30,'Brezilya'),
('Çorum Leblebi',2,'Erhan Erentürk','Erhan Erentürko','GK',31,'Türkiye'),
('Çorum Leblebi',3,'Çağlar Söyüncü','Çağlar Söyünco','DEF',30,'Türkiye'),
('Çorum Leblebi',4,'Hrvoje Smolcic','Hrvoje Smolcico','DEF',26,'Hırvatistan'),
('Çorum Leblebi',5,'Serdar Saatçı','Serdar Saatçın','DEF',23,'Türkiye'),
('Çorum Leblebi',6,'Andrei Borza','Andrei Borzan','DEF',20,'Romanya'),
('Çorum Leblebi',7,'Gökhan Sazdağı','Gökhan Sazdağın','DEF',32,'Türkiye'),
('Çorum Leblebi',8,'Cemali Sertel','Cemali Sertelo','DEF',26,'Türkiye'),
('Çorum Leblebi',9,'Alexandre Penetra','Alexandre Penetran','DEF',25,'Portekiz'),
('Çorum Leblebi',10,'Mohamed Diomande','Mohamed Diomanden','MID',24,'Fildişi Sahili'),
('Çorum Leblebi',11,'Fredy','Fredyo','MID',36,'Angola'),
('Çorum Leblebi',12,'Berat Özdemir','Berat Özdemiro','MID',28,'Türkiye'),
('Çorum Leblebi',13,'Ylber Ramadani','Ylber Ramadanin','MID',30,'Arnavutluk'),
('Çorum Leblebi',14,'Markus Karlsbakk','Markus Karlsbakko','MID',26,'Norveç'),
('Çorum Leblebi',15,'Ahmed Ildız','Ahmed Ildızz','MID',29,'Türkiye'),
('Çorum Leblebi',16,'Göktan Gürpüz','Göktan Gürpüzz','MID',23,'Türkiye'),
('Çorum Leblebi',17,'Mame Baba Thiam','Mame Baba Tiyam','FWD',33,'Senegal'),
('Çorum Leblebi',18,'Youssoufa Moukoko','Yusu Moukoko','FWD',21,'Almanya'),
('Çorum Leblebi',19,'Alexandros Kyziridis','Alexandros Kyziridiso','FWD',26,'Yunanistan'),
('Çorum Leblebi',20,'Jesus Ramirez','Jesus Ramirezz','FWD',28,'Venezuela'),
('Çorum Leblebi',21,'Cengiz Ünder','Cengiz Ündero','FWD',29,'Türkiye'),
('Çorum Leblebi',22,'Emircan Gürlük','Emircan Gürlüko','FWD',22,'Türkiye');

-- Every player in Afyon is fictional/parody.
update public.players
set is_parody=true,
    roster_season='2026-27';

-- Localized fictional names for every non-Türkiye-Crown player.
-- Three squad slots (8, 17, 22) are foreign imports; the rest follow the club country's naming style.
with x as (
  select p.id,p.club_id,c.country,c.league_level,
         regexp_replace(p.id,'^.*\|','')::int as slot,
         (hashtextextended(p.id,19) & 9223372036854775807) as h
  from public.players p
  join public.clubs c on c.id=p.club_id
  where not (c.country='Türkiye' and c.league_level=1)
),
names as (
  select x.*,
    (slot in (8,17,22)) as foreign_slot,
    case country
      when 'Türkiye' then array['Aras','Ali','Poyraz','Mert','Emir','Kerem','Eren','Bora','Doruk','Can','Yiğit','Oğuz','Kaan','Umut','Baran','Berke','Deniz','Tuna']
      when 'İngiltere' then array['Jack','Harry','Oliver','George','Alfie','Charlie','Liam','Mason','Ethan','Callum','Jamie','Lewis','Archie','Finley','Theo','Max','Ben','Sam']
      when 'İspanya' then array['Mateo','Hugo','Pablo','Diego','Sergio','Iker','Adrian','Alejandro','Nico','Ivan','Raul','Javi','Marco','Dani','Alex','Mario','Unai','Leo']
      when 'Almanya' then array['Lukas','Jonas','Felix','Maximilian','Leon','Niklas','Florian','Julian','Timo','Moritz','Finn','Paul','Anton','David','Noah','Emil','Mats','Kai']
      when 'İtalya' then array['Luca','Marco','Matteo','Andrea','Federico','Nicolo','Alessio','Davide','Simone','Tommaso','Riccardo','Gabriele','Pietro','Lorenzo','Filippo','Edoardo','Samuele','Elia']
      when 'Fransa' then array['Theo','Hugo','Lucas','Jules','Louis','Adrien','Mathis','Enzo','Maxime','Antoine','Noe','Rayan','Yanis','Kylian','Bastien','Remy','Axel','Loic']
      when 'Hollanda' then array['Daan','Jesse','Lars','Mats','Sem','Thijs','Luuk','Bram','Mees','Jelle','Sven','Niels','Teun','Wout','Koen','Joep','Finn','Timo']
      when 'Portekiz' then array['Tiago','Rui','Joao','Diogo','Goncalo','Andre','Miguel','Pedro','Tomas','Nuno','Afonso','Ricardo','Bruno','Fabio','Duarte','Vasco','Henrique','Luis']
      when 'Belçika' then array['Arthur','Louis','Jules','Mathis','Noah','Victor','Milan','Seppe','Lars','Wout','Robbe','Jarne','Tibo','Maxime','Niels','Bram','Lucas','Emile']
      when 'İskoçya' then array['Callum','Lewis','Ryan','Scott','Jamie','Ross','Ewan','Finlay','Connor','Liam','Craig','Fraser','Dylan','Jack','Cameron','Kieran','Aidan','Rory']
      when 'Yunanistan' then array['Nikos','Giorgos','Dimitris','Kostas','Manolis','Petros','Vasilis','Alexis','Stavros','Yannis','Thanos','Michalis','Andreas','Sotiris','Christos','Panos','Spiros','Leonidas']
      when 'Avusturya' then array['Lukas','Florian','Dominik','Matthias','Sebastian','Felix','Jakob','David','Simon','Tobias','Moritz','Paul','Maximilian','Niklas','Fabian','Leon','Alexander','Julian']
      else array['Alex','Leo','Max','Nico','Sam','Tom','Dan','Ben','Kai','Ian','Noah','Liam','Theo','Milo','Eli','Oli','Jan','Luca']
    end as firsts,
    case country
      when 'Türkiye' then array['Demir','Poyraz','Aydın','Kaya','Yıldız','Arslan','Çetin','Koç','Şahin','Aksoy','Kurt','Öztürk','Karaca','Güneş','Duman','Erdem','Bulut','Tekin']
      when 'İngiltere' then array['Baker','Turner','Cooper','Walker','Parker','Foster','Carter','Miller','Wilson','Taylor','Collins','Morgan','Hughes','Bennett','Ward','Reed','Hall','Brooks']
      when 'İspanya' then array['Ruiz','Navarro','Santos','Molina','Vega','Ramos','Ortega','Castro','Iglesias','Moreno','Soler','Cano','Rojas','Vidal','Mendez','Prieto','Lozano','Cruz']
      when 'Almanya' then array['Weber','Klein','Fischer','Wagner','Krause','Becker','Schulz','Wolf','Hartmann','Vogel','Keller','Bauer','Neumann','Brandt','Kuhn','Jager','Maier','Stein']
      when 'İtalya' then array['Romano','Bianchi','Conti','Rossi','Ferrari','Gallo','Costa','Moretti','Lombardi','Greco','Marino','Rinaldi','Caruso','Vitale','De Luca','Serra','Fontana','Leone']
      when 'Fransa' then array['Bernard','Moreau','Petit','Dubois','Leroy','Roux','Fontaine','Mercier','Garnier','Chevalier','Blanc','Robin','Perrot','Masson','Colin','Renard','Barbier','Marchand']
      when 'Hollanda' then array['de Vries','Bakker','Jansen','Smit','Visser','de Boer','Mulder','Meijer','Bos','Vos','Dekker','Dijkstra','Kuiper','de Jong','Vermeer','Koster','van Dijk','Hoek']
      when 'Portekiz' then array['Silva','Costa','Pereira','Santos','Ferreira','Rodrigues','Oliveira','Sousa','Martins','Almeida','Correia','Teixeira','Rocha','Neves','Coelho','Mendes','Pinto','Ribeiro']
      when 'Belçika' then array['Peeters','Maes','Jacobs','Willems','Mertens','Claes','Goossens','Wouters','Vermeulen','Aerts','De Smet','Vandamme','Vercauteren','Lemmens','Devos','Dierckx','Baert','Verhoeven']
      when 'İskoçya' then array['MacLeod','Campbell','Stewart','Murray','Fraser','McKay','Hamilton','Robertson','Douglas','Graham','Ferguson','Kerr','Morrison','Cameron','Johnston','Sinclair','Munro','Boyd']
      when 'Yunanistan' then array['Papadopoulos','Nikolaou','Georgiou','Vlachos','Pappas','Kostas','Manolas','Raptis','Karalis','Zafeiris','Kouris','Theodorou','Markou','Sarris','Loukas','Tzimas','Vrettos','Dimas']
      when 'Avusturya' then array['Gruber','Huber','Bauer','Wagner','Moser','Steiner','Hofer','Berger','Fuchs','Leitner','Eder','Schmid','Mayr','Pichler','Koller','Auer','Winter','Hauser']
      else array['Smith','Silva','Costa','Martin','Rossi','Weber','Santos','Brown','Taylor','Lopez','Muller','Garcia','Wilson','Pereira','Jones','Mendes','Klein','Moreau']
    end as lasts
  from x
),
built as (
  select n.*,
    case
      when foreign_slot then
        (array['Mateo','Rayan','Milo','Adama','Luka','Noah','Samu','Ibra','Nico','Leo','Yuri','Dario'])[1+((h/31)%12)::int]
        || ' ' ||
        (array['Silva','Kone','Petrovic','Mensah','Costa','Diallo','Jovic','Ndiaye','Rossi','Santos','Mendes','Traore'])[1+((h/47)%12)::int]
      else firsts[1+((h/29)%array_length(firsts,1))::int] || ' ' || lasts[1+((h/43)%array_length(lasts,1))::int]
    end as new_name,
    case
      when not foreign_slot then country
      else (array['Brezilya','Nijerya','Sırbistan','Fransa','Portekiz','Gana','Hırvatistan','Senegal'])[1+((h/59)%8)::int]
    end as new_nat
  from names n
)
update public.players p
set display_name=b.new_name,
    nationality=b.new_nat,
    source_player_name=null,
    is_roster_mirror=false,
    is_star_parody=false,
    roster_season='2026-27'
from built b
where p.id=b.id;

-- Apply current-season analogue rosters to all 18 Türkiye Crown clubs.
with t as (
  select prt.*,c.id club_id,c.overall club_overall
  from private.player_roster_templates prt
  join public.clubs c on c.name=prt.club_name
  where c.country='Türkiye' and c.league_level=1 and prt.season='2026-27'
),
ranked as (
  select t.*,
    case position
      when 'GK' then case slot when 1 then 1 else -3 end
      when 'DEF' then (array[3,2,1,0,-1,-2,-3])[slot-2]
      when 'MID' then (array[4,3,2,1,0,-2,-3])[slot-9]
      when 'FWD' then (array[5,3,2,0,-2,-3])[slot-16]
    end as delta
  from t
)
update public.players p
set display_name=r.parody_name,
    source_player_name=r.source_player_name,
    position=r.position,
    nationality=r.nationality,
    age=r.age,
    overall=greatest(20,least(97,round(r.club_overall)::int+r.delta)),
    potential=greatest(greatest(20,least(97,round(r.club_overall)::int+r.delta)),
      least(99,greatest(20,least(97,round(r.club_overall)::int+r.delta)) +
        case when r.age<=21 then 6 when r.age<=24 then 4 when r.age<=27 then 2 else 0 end)),
    form=55+((hashtextextended(p.id,31) & 9223372036854775807)%21)::int,
    morale=58+((hashtextextended(p.id,37) & 9223372036854775807)%25)::int,
    fitness=90+((hashtextextended(p.id,41) & 9223372036854775807)%11)::int,
    injury_weeks=0,
    roster_season='2026-27',
    is_parody=true,
    is_star_parody=true,
    is_roster_mirror=true
from ranked r
where p.club_id=r.club_id
  and regexp_replace(p.id,'^.*\|','')::int=r.slot;

-- Rebuild technical attributes from the new overall/position values.
update public.players p
set
  finishing=greatest(20,least(99,p.overall + case p.position when 'FWD' then 7 when 'MID' then 1 when 'DEF' then -9 else -25 end)),
  passing=greatest(20,least(99,p.overall + case p.position when 'MID' then 6 when 'FWD' then 1 when 'DEF' then 1 else -4 end)),
  dribbling=greatest(20,least(99,p.overall + case p.position when 'FWD' then 4 when 'MID' then 4 when 'DEF' then -5 else -20 end)),
  tackling=greatest(20,least(99,p.overall + case p.position when 'DEF' then 7 when 'MID' then 1 when 'FWD' then -8 else -12 end)),
  pace=greatest(20,least(99,p.overall + case p.position when 'FWD' then 4 when 'DEF' then 1 when 'MID' then 0 else -8 end)),
  strength=greatest(20,least(99,p.overall + case p.position when 'DEF' then 4 when 'FWD' then 2 when 'GK' then 1 else 0 end)),
  goalkeeping=greatest(20,least(99,p.overall + case p.position when 'GK' then 8 else -32 end));

